
const cards = [
  { root: 'ir', tense: 'present indicative',       subject: 'eu',   conjugation: 'vou',   frase: 'a aula.', en: 'go',         sentence: 'to class.', regular: false },
  { root: 'ir', tense: 'present indicative',       subject: 'voce', conjugation: 'vai',   frase: 'a aula.', en: 'go',         sentence: 'to class.', regular: false },
  { root: 'ir', tense: 'present indicative',       subject: 'elas', conjugation: 'vão',   frase: 'a aula.', en: 'go',         sentence: 'to class.', regular: false },
  { root: 'ir', tense: 'past perfect',          subject: 'eu',   conjugation: 'fui',   frase: 'a aula.', en: 'went',       sentence: 'to class.', regular: false },
  { root: 'ir', tense: 'past perfect',          subject: 'voce', conjugation: 'foi',   frase: 'a aula.', en: 'went',       sentence: 'to class.', regular: false },
  { root: 'ir', tense: 'past perfect',          subject: 'elas', conjugation: 'foram', frase: 'a aula.', en: 'went',       sentence: 'to class.', regular: false },
  { root: 'ir', tense: 'past imperfect', subject: 'eu',   conjugation: 'ia',    frase: 'a aula.', en: 'used to go', sentence: 'to class.', regular: false },
  { root: 'ir', tense: 'past imperfect', subject: 'voce', conjugation: 'ia',    frase: 'a aula.', en: 'used to go', sentence: 'to class.', regular: false },
  { root: 'ir', tense: 'past imperfect', subject: 'elas', conjugation: 'iam',   frase: 'a aula.', en: 'used to go', sentence: 'to class.', regular: false },

  { root: 'ser', tense: 'present indicative',       subject: 'eu',   conjugation: 'sou',   frase: 'inteligente.',  en: 'am',         sentence: 'intelligent.', regular: false },
  { root: 'ser', tense: 'present indicative',       subject: 'voce', conjugation: 'é',     frase: 'inteligente.',  en: 'are',        sentence: 'intelligent.', regular: false },
  { root: 'ser', tense: 'present indicative',       subject: 'elas', conjugation: 'são',   frase: 'inteligentes.', en: 'are',        sentence: 'intelligent.', regular: false },
  { root: 'ser', tense: 'past perfect',          subject: 'eu',   conjugation: 'fui',   frase: 'inteligente.',  en: 'was',        sentence: 'intelligent.', regular: false },
  { root: 'ser', tense: 'past perfect',          subject: 'voce', conjugation: 'foi',   frase: 'inteligente.',  en: 'were',       sentence: 'intelligent.', regular: false },
  { root: 'ser', tense: 'past perfect',          subject: 'elas', conjugation: 'foram', frase: 'inteligentes.', en: 'were',       sentence: 'intelligent.', regular: false },
  { root: 'ser', tense: 'past imperfect', subject: 'eu',   conjugation: 'era',   frase: 'inteligente.',  en: 'used to be', sentence: 'intelligent.', regular: false },
  { root: 'ser', tense: 'past imperfect', subject: 'voce', conjugation: 'era',   frase: 'inteligente.',  en: 'used to be', sentence: 'intelligent.', regular: false },
  { root: 'ser', tense: 'past imperfect', subject: 'elas', conjugation: 'eram',  frase: 'inteligentes.', en: 'used to be', sentence: 'intelligent.', regular: false },

  { root: 'estar', tense: 'present indicative',       subject: 'eu',   conjugation: 'estou',     frase: 'no Brasil.', en: 'am',         sentence: 'in Brazil.', regular: false },
  { root: 'estar', tense: 'present indicative',       subject: 'voce', conjugation: 'està',      frase: 'no Brasil.', en: 'are',        sentence: 'in Brazil.', regular: false },
  { root: 'estar', tense: 'present indicative',       subject: 'elas', conjugation: 'estão',     frase: 'no Brasil.', en: 'are',        sentence: 'in Brazil.', regular: false },
  { root: 'estar', tense: 'past perfect',          subject: 'eu',   conjugation: 'estive',    frase: 'no Brasil.', en: 'was',        sentence: 'in Brazil.', regular: false },
  { root: 'estar', tense: 'past perfect',          subject: 'voce', conjugation: 'esteve',    frase: 'no Brasil.', en: 'were',       sentence: 'in Brazil.', regular: false },
  { root: 'estar', tense: 'past perfect',          subject: 'elas', conjugation: 'estiveram', frase: 'no Brasil.', en: 'were',       sentence: 'in Brazil.', regular: false },
  { root: 'estar', tense: 'past imperfect', subject: 'eu',   conjugation: 'estava',    frase: 'no Brasil.', en: 'used to be', sentence: 'in Brazil.', regular: true },
  { root: 'estar', tense: 'past imperfect', subject: 'voce', conjugation: 'estava',    frase: 'no Brasil.', en: 'used to be', sentence: 'in Brazil.', regular: true },
  { root: 'estar', tense: 'past imperfect', subject: 'elas', conjugation: 'estavam',   frase: 'no Brasil.', en: 'used to be', sentence: 'in Brazil.', regular: true },

  { root: 'ter', tense: 'present indicative',       subject: 'eu',   conjugation: 'tenho',   frase: 'um sonho.', en: 'have',         sentence: 'a dream.', regular: false },
  { root: 'ter', tense: 'present indicative',       subject: 'voce', conjugation: 'tem',     frase: 'um sonho.', en: 'have',         sentence: 'a dream.', regular: false },
  { root: 'ter', tense: 'present indicative',       subject: 'elas', conjugation: 'têm',     frase: 'um sonho.', en: 'have',         sentence: 'a dream.', regular: false },
  { root: 'ter', tense: 'past perfect',          subject: 'eu',   conjugation: 'tive',    frase: 'um sonho.', en: 'had',          sentence: 'a dream.', regular: false },
  { root: 'ter', tense: 'past perfect',          subject: 'voce', conjugation: 'teve',    frase: 'um sonho.', en: 'had',          sentence: 'a dream.', regular: false },
  { root: 'ter', tense: 'past perfect',          subject: 'elas', conjugation: 'tiveram', frase: 'um sonho.', en: 'had',          sentence: 'a dream.', regular: false },
  { root: 'ter', tense: 'past imperfect', subject: 'eu',   conjugation: 'tinha',   frase: 'um sonho.', en: 'used to have', sentence: 'a dream.', regular: false },
  { root: 'ter', tense: 'past imperfect', subject: 'voce', conjugation: 'tinha',   frase: 'um sonho.', en: 'used to have', sentence: 'a dream.', regular: false },
  { root: 'ter', tense: 'past imperfect', subject: 'elas', conjugation: 'tinham',  frase: 'um sonho.', en: 'used to have', sentence: 'a dream.', regular: false },

  { root: 'trazer', tense: 'present indicative',       subject: 'eu',   conjugation: 'trago',   frase: 'um lápis a aula.', en: 'bring',         sentence: 'a pencil to class.', regular: false },
  { root: 'trazer', tense: 'present indicative',       subject: 'voce', conjugation: 'traz',    frase: 'um lápis a aula.', en: 'bring',         sentence: 'a pencil to class.', regular: false },
  { root: 'trazer', tense: 'present indicative',       subject: 'elas', conjugation: 'trazem',  frase: 'um lápis a aula.', en: 'bring',         sentence: 'a pencil to class.', regular: true },
  { root: 'trazer', tense: 'past perfect',          subject: 'eu',   conjugation: 'trouxe',  frase: 'um lápis a aula.', en: 'brought',       sentence: 'a pencil to class.', regular: false },
  { root: 'trazer', tense: 'past perfect',          subject: 'voce', conjugation: 'trouxe',  frase: 'um lápis a aula.', en: 'brought',       sentence: 'a pencil to class.', regular: false },
  { root: 'trazer', tense: 'past perfect',          subject: 'elas', conjugation: 'trouxe',  frase: 'um lápis a aula.', en: 'brought',       sentence: 'a pencil to class.', regular: false },
  { root: 'trazer', tense: 'past imperfect', subject: 'eu',   conjugation: 'trazia',  frase: 'um lápis a aula.', en: 'used to bring', sentence: 'a pencil to class.', regular: true },
  { root: 'trazer', tense: 'past imperfect', subject: 'voce', conjugation: 'trazia',  frase: 'um lápis a aula.', en: 'used to bring', sentence: 'a pencil to class.', regular: true },
  { root: 'trazer', tense: 'past imperfect', subject: 'elas', conjugation: 'traziam', frase: 'um lápis a aula.', en: 'used to bring', sentence: 'a pencil to class.', regular: true },

  { root: 'levar', tense: 'present indicative',       subject: 'eu',   conjugation: 'levo',    frase: 'minha amiga pra LA.', en: 'take',         sentence: 'my friend to LA.', regular: true },
  { root: 'levar', tense: 'present indicative',       subject: 'voce', conjugation: 'leva',    frase: 'minha amiga pra LA.', en: 'take',         sentence: 'my friend to LA.', regular: true },
  { root: 'levar', tense: 'present indicative',       subject: 'elas', conjugation: 'levam',   frase: 'minha amiga pra LA.', en: 'take',         sentence: 'my friend to LA.', regular: true },
  { root: 'levar', tense: 'past perfect',          subject: 'eu',   conjugation: 'levei',   frase: 'minha amiga pra LA.', en: 'took',         sentence: 'my friend to LA.', regular: true },
  { root: 'levar', tense: 'past perfect',          subject: 'voce', conjugation: 'levou',   frase: 'minha amiga pra LA.', en: 'took',         sentence: 'my friend to LA.', regular: true },
  { root: 'levar', tense: 'past perfect',          subject: 'elas', conjugation: 'levaram', frase: 'minha amiga pra LA.', en: 'took',         sentence: 'my friend to LA.', regular: true },
  { root: 'levar', tense: 'past imperfect', subject: 'eu',   conjugation: 'levava',  frase: 'minha amiga pra LA.', en: 'used to take', sentence: 'my friend to LA.', regular: true },
  { root: 'levar', tense: 'past imperfect', subject: 'voce', conjugation: 'levava',  frase: 'minha amiga pra LA.', en: 'used to take', sentence: 'my friend to LA.', regular: true },
  { root: 'levar', tense: 'past imperfect', subject: 'elas', conjugation: 'levavam', frase: 'minha amiga pra LA.', en: 'used to take', sentence: 'my friend to LA.', regular: true },

  { root: 'fazer', tense: 'present indicative',       subject: 'eu',   conjugation: 'faco',    frase: 'alguns lição de casa.', en: 'do',         sentence: 'some homework.', regular: false },
  { root: 'fazer', tense: 'present indicative',       subject: 'voce', conjugation: 'faz',     frase: 'alguns lição de casa.', en: 'do',         sentence: 'some homework.', regular: false },
  { root: 'fazer', tense: 'present indicative',       subject: 'elas', conjugation: 'fazem',   frase: 'alguns lição de casa.', en: 'do',         sentence: 'some homework.', regular: true },
  { root: 'fazer', tense: 'past perfect',          subject: 'eu',   conjugation: 'fiz',     frase: 'alguns lição de casa.', en: 'did',        sentence: 'some homework.', regular: false },
  { root: 'fazer', tense: 'past perfect',          subject: 'voce', conjugation: 'fez',     frase: 'alguns lição de casa.', en: 'did',        sentence: 'some homework.', regular: false },
  { root: 'fazer', tense: 'past perfect',          subject: 'elas', conjugation: 'fizeram', frase: 'alguns lição de casa.', en: 'did',        sentence: 'some homework.', regular: false },
  { root: 'fazer', tense: 'past imperfect', subject: 'eu',   conjugation: 'fazia',   frase: 'alguns lição de casa.', en: 'used to do', sentence: 'some homework.', regular: true },
  { root: 'fazer', tense: 'past imperfect', subject: 'voce', conjugation: 'fazia',   frase: 'alguns lição de casa.', en: 'used to do', sentence: 'some homework.', regular: true },
  { root: 'fazer', tense: 'past imperfect', subject: 'elas', conjugation: 'faziam',  frase: 'alguns lição de casa.', en: 'used to do', sentence: 'some homework.', regular: true },

  { root: 'saber', tense: 'present indicative',       subject: 'eu',   conjugation: 'sei',      frase: 'falar Portuguese.', en: 'know',         sentence: 'how to speak Portuguese.', regular: false },
  { root: 'saber', tense: 'present indicative',       subject: 'voce', conjugation: 'sabe',     frase: 'falar Portuguese.', en: 'know',         sentence: 'how to speak Portuguese.', regular: true },
  { root: 'saber', tense: 'present indicative',       subject: 'elas', conjugation: 'sabem',    frase: 'falar Portuguese.', en: 'know',         sentence: 'how to speak Portuguese.', regular: true },
  { root: 'saber', tense: 'past perfect',          subject: 'eu',   conjugation: 'soube',    frase: 'falar Portuguese.', en: 'knew',         sentence: 'how to speak Portuguese.', regular: false },
  { root: 'saber', tense: 'past perfect',          subject: 'voce', conjugation: 'soube',    frase: 'falar Portuguese.', en: 'knew',         sentence: 'how to speak Portuguese.', regular: false },
  { root: 'saber', tense: 'past perfect',          subject: 'elas', conjugation: 'souberam', frase: 'falar Portuguese.', en: 'knew',         sentence: 'how to speak Portuguese.', regular: false },
  { root: 'saber', tense: 'past imperfect', subject: 'eu',   conjugation: 'sabia',    frase: 'falar Portuguese.', en: 'used to know', sentence: 'how to speak Portuguese.', regular: true },
  { root: 'saber', tense: 'past imperfect', subject: 'voce', conjugation: 'sabia',    frase: 'falar Portuguese.', en: 'used to know', sentence: 'how to speak Portuguese.', regular: true },
  { root: 'saber', tense: 'past imperfect', subject: 'elas', conjugation: 'sabiam',   frase: 'falar Portuguese.', en: 'used to know', sentence: 'how to speak Portuguese.', regular: true },

  // { root: 'querer', tense: 'present indicative',       subject: 'eu',   conjugation: 'quero',    frase: 'falar Portuguese.', en: 'want',         sentence: 'how to speak Portuguese.', regular: true },
  // { root: 'querer', tense: 'present indicative',       subject: 'voce', conjugation: 'quer',     frase: 'falar Portuguese.', en: 'want',         sentence: 'how to speak Portuguese.', regular: false },
  // { root: 'querer', tense: 'present indicative',       subject: 'elas', conjugation: 'querem',   frase: 'falar Portuguese.', en: 'want',         sentence: 'how to speak Portuguese.', regular: true },
  // { root: 'querer', tense: 'past perfect',          subject: 'eu',   conjugation: 'quis',     frase: 'falar Portuguese.', en: 'wanted',       sentence: 'how to speak Portuguese.', regular: false },
  // { root: 'querer', tense: 'past perfect',          subject: 'voce', conjugation: 'quis',     frase: 'falar Portuguese.', en: 'wanted',       sentence: 'how to speak Portuguese.', regular: false },
  // { root: 'querer', tense: 'past perfect',          subject: 'elas', conjugation: 'quiseram', frase: 'falar Portuguese.', en: 'wanted',       sentence: 'how to speak Portuguese.', regular: false },
  // { root: 'querer', tense: 'past imperfect', subject: 'eu',   conjugation: 'queria',   frase: 'falar Portuguese.', en: 'used to want', sentence: 'how to speak Portuguese.', regular: true },
  // { root: 'querer', tense: 'past imperfect', subject: 'voce', conjugation: 'queria',   frase: 'falar Portuguese.', en: 'used to want', sentence: 'how to speak Portuguese.', regular: true },
  // { root: 'querer', tense: 'past imperfect', subject: 'elas', conjugation: 'queria',   frase: 'falar Portuguese.', en: 'used to want', sentence: 'how to speak Portuguese.', regular: true },

  { root: 'vir', tense: 'present indicative',       subject: 'eu',   conjugation: 'venho',  frase: 'pra escola.', en: 'come',         sentence: 'to school.', regular: false },
  { root: 'vir', tense: 'present indicative',       subject: 'voce', conjugation: 'vem',    frase: 'pra escola.', en: 'come',         sentence: 'to school.', regular: false },
  { root: 'vir', tense: 'present indicative',       subject: 'elas', conjugation: 'vêm',    frase: 'pra escola.', en: 'come',         sentence: 'to school.', regular: false },
  { root: 'vir', tense: 'past perfect',          subject: 'eu',   conjugation: 'vim',    frase: 'pra escola.', en: 'came',         sentence: 'to school.', regular: false },
  { root: 'vir', tense: 'past perfect',          subject: 'voce', conjugation: 'veio',   frase: 'pra escola.', en: 'came',         sentence: 'to school.', regular: false },
  { root: 'vir', tense: 'past perfect',          subject: 'elas', conjugation: 'vieram', frase: 'pra escola.', en: 'came',         sentence: 'to school.', regular: false },
  { root: 'vir', tense: 'past imperfect', subject: 'eu',   conjugation: 'vinha',  frase: 'pra escola.', en: 'used to come', sentence: 'to school.', regular: false },
  { root: 'vir', tense: 'past imperfect', subject: 'voce', conjugation: 'vinha',  frase: 'pra escola.', en: 'used to come', sentence: 'to school.', regular: false },
  { root: 'vir', tense: 'past imperfect', subject: 'elas', conjugation: 'vinham', frase: 'pra escola.', en: 'used to come', sentence: 'to school.', regular: false },

  { root: 'ver', tense: 'present indicative',       subject: 'eu',   conjugation: 'vejo',  frase: 'um homem bonito.', en: 'see',         sentence: 'a handsome man.', regular: false },
  { root: 'ver', tense: 'present indicative',       subject: 'voce', conjugation: 'vê',    frase: 'um homem bonito.', en: 'see',         sentence: 'a handsome man.', regular: false },
  { root: 'ver', tense: 'present indicative',       subject: 'elas', conjugation: 'veem',  frase: 'um homem bonito.', en: 'see',         sentence: 'a handsome man.', regular: false },
  { root: 'ver', tense: 'past perfect',          subject: 'eu',   conjugation: 'vi',    frase: 'um homem bonito.', en: 'saw',         sentence: 'a handsome man.', regular: true },
  { root: 'ver', tense: 'past perfect',          subject: 'voce', conjugation: 'viu',   frase: 'um homem bonito.', en: 'saw',         sentence: 'a handsome man.', regular: false },
  { root: 'ver', tense: 'past perfect',          subject: 'elas', conjugation: 'viram', frase: 'um homem bonito.', en: 'saw',         sentence: 'a handsome man.', regular: false },
  { root: 'ver', tense: 'past imperfect', subject: 'eu',   conjugation: 'via',   frase: 'um homem bonito.', en: 'used to see', sentence: 'a handsome man.', regular: true },
  { root: 'ver', tense: 'past imperfect', subject: 'voce', conjugation: 'via',   frase: 'um homem bonito.', en: 'used to see', sentence: 'a handsome man.', regular: true },
  { root: 'ver', tense: 'past imperfect', subject: 'elas', conjugation: 'viam',  frase: 'um homem bonito.', en: 'used to see', sentence: 'a handsome man.', regular: true },

  { root: 'poder', tense: 'present indicative',       subject: 'eu',   conjugation: 'posso',   frase: 'entrar.',                en: 'can',          sentence: 'go inside.',           regular: false },
  { root: 'poder', tense: 'present indicative',       subject: 'voce', conjugation: 'pode',    frase: 'entrar.',                en: 'can',          sentence: 'go inside.',           regular: true },
  { root: 'poder', tense: 'present indicative',       subject: 'elas', conjugation: 'podem',   frase: 'entrar.',                en: 'can',          sentence: 'go inside.',           regular: true },
  { root: 'poder', tense: 'past perfect',          subject: 'eu',   conjugation: 'pude',    frase: 'assistir a esse filme.', en: 'was able to',  sentence: 'watch this movie.',    regular: false },
  { root: 'poder', tense: 'past perfect',          subject: 'voce', conjugation: 'pôde',    frase: 'assistir a esse filme.', en: 'were able to', sentence: 'watch this movie.',    regular: false },
  { root: 'poder', tense: 'past perfect',          subject: 'elas', conjugation: 'puderam', frase: 'assistir a esse filme.', en: 'were able to', sentence: 'watch this movie.',    regular: false },
  { root: 'poder', tense: 'past imperfect', subject: 'eu',   conjugation: 'podia',   frase: 'entrar.',                en: 'could',        sentence: 'go inside yesterday.', regular: true },
  { root: 'poder', tense: 'past imperfect', subject: 'voce', conjugation: 'podia',   frase: 'entrar.',                en: 'could',        sentence: 'go inside yesterday.', regular: true },
  { root: 'poder', tense: 'past imperfect', subject: 'elas', conjugation: 'podiam',  frase: 'entrar.',                en: 'could',        sentence: 'go inside yesterday.', regular: true },

  { root: 'dizer', tense: 'present indicative',       subject: 'eu',   conjugation: 'digo',     frase: '"olá" todas as manhãs.', en: 'say',         sentence: '"hello" every morning.', regular: false },
  { root: 'dizer', tense: 'present indicative',       subject: 'voce', conjugation: 'diz',      frase: '"olá" todas as manhãs.', en: 'says',        sentence: '"hello" every morning.', regular: false },
  { root: 'dizer', tense: 'present indicative',       subject: 'elas', conjugation: 'dizem',    frase: '"olá" todas as manhãs.', en: 'say',         sentence: '"hello" every morning.', regular: true },
  { root: 'dizer', tense: 'past perfect',          subject: 'eu',   conjugation: 'disse',    frase: '"olá" ontem.',           en: 'said',        sentence: '"hello" yesterday.',     regular: false },
  { root: 'dizer', tense: 'past perfect',          subject: 'voce', conjugation: 'disse',    frase: '"olá" ontem.',           en: 'said',        sentence: '"hello" yesterday.',     regular: false },
  { root: 'dizer', tense: 'past perfect',          subject: 'elas', conjugation: 'disseram', frase: '"olá" ontem.',           en: 'said',        sentence: '"hello" yesterday.',     regular: false },
  { root: 'dizer', tense: 'past imperfect', subject: 'eu',   conjugation: 'dizia',    frase: '"viva e Deixe Viver."',  en: 'used to say', sentence: '"live and let live."',   regular: true },
  { root: 'dizer', tense: 'past imperfect', subject: 'voce', conjugation: 'dizia',    frase: '"viva e Deixe Viver."',  en: 'used to say', sentence: '"live and let live."',   regular: true },
  { root: 'dizer', tense: 'past imperfect', subject: 'elas', conjugation: 'diziam',   frase: '"viva e Deixe Viver."',  en: 'used to say', sentence: '"live and let live."',   regular: true },

  // { root: 'gostar', tense: 'present indicative',       subject: 'eu',   conjugation: 'digo', frase: '"olá" todas as manhãs.', en: 'can', sentence: '"hello" every morning.', regular: false },
  // { root: 'gostar', tense: 'present indicative',       subject: 'voce', conjugation: 'diz', frase: '"olá" todas as manhãs.', en: 'can', sentence: '"hello" every morning.', regular: false },
  // { root: 'gostar', tense: 'present indicative',       subject: 'elas', conjugation: 'dizem', frase: '"olá" todas as manhãs.', en: 'can', sentence: '"hello" every morning.', regular: false },
  // { root: 'gostar', tense: 'past perfect',          subject: 'eu',   conjugation: 'disse', frase: '"olá" ontem.', en: 'was able to', sentence: '"hello" yesterday.', regular: false },
  // { root: 'gostar', tense: 'past perfect',          subject: 'voce', conjugation: 'disse', frase: '"olá" ontem.', en: 'was able to', sentence: '"hello" yesterday.', regular: false },
  // { root: 'gostar', tense: 'past perfect',          subject: 'elas', conjugation: 'disseram', frase: '"olá" ontem.', en: 'was able to', sentence: '"hello" yesterday.', regular: false },
  // { root: 'gostar', tense: 'past imperfect', subject: 'eu',   conjugation: 'dizia', frase: '"viva e Deixe Viver."', en: 'could', sentence: '"live and let live."', regular: false },
  // { root: 'gostar', tense: 'past imperfect', subject: 'voce', conjugation: 'dizia', frase: '"viva e Deixe Viver."', en: 'could', sentence: '"live and let live."', regular: false },
  // { root: 'gostar', tense: 'past imperfect', subject: 'elas', conjugation: 'diziam', frase: '"viva e Deixe Viver."', en: 'could', sentence: '"live and let live."', regular: false },

  // { root: 'tentar', tense: 'present indicative',       subject: 'eu',   conjugation: 'digo', frase: '"olá" todas as manhãs.', en: 'can', sentence: '"hello" every morning.', regular: false },
  // { root: 'tentar', tense: 'present indicative',       subject: 'voce', conjugation: 'diz', frase: '"olá" todas as manhãs.', en: 'can', sentence: '"hello" every morning.', regular: false },
  // { root: 'tentar', tense: 'present indicative',       subject: 'elas', conjugation: 'dizem', frase: '"olá" todas as manhãs.', en: 'can', sentence: '"hello" every morning.', regular: false },
  // { root: 'tentar', tense: 'past perfect',          subject: 'eu',   conjugation: 'disse', frase: '"olá" ontem.', en: 'was able to', sentence: '"hello" yesterday.', regular: false },
  // { root: 'tentar', tense: 'past perfect',          subject: 'voce', conjugation: 'disse', frase: '"olá" ontem.', en: 'was able to', sentence: '"hello" yesterday.', regular: false },
  // { root: 'tentar', tense: 'past perfect',          subject: 'elas', conjugation: 'disseram', frase: '"olá" ontem.', en: 'was able to', sentence: '"hello" yesterday.', regular: false },
  // { root: 'tentar', tense: 'past imperfect', subject: 'eu',   conjugation: 'dizia', frase: '"viva e Deixe Viver."', en: 'could', sentence: '"live and let live."', regular: false },
  // { root: 'tentar', tense: 'past imperfect', subject: 'voce', conjugation: 'dizia', frase: '"viva e Deixe Viver."', en: 'could', sentence: '"live and let live."', regular: false },
  // { root: 'tentar', tense: 'past imperfect', subject: 'elas', conjugation: 'diziam', frase: '"viva e Deixe Viver."', en: 'could', sentence: '"live and let live."', regular: false },

  // { root: 'tocar', tense: 'present indicative',       subject: 'eu',   conjugation: 'digo', frase: '"olá" todas as manhãs.', en: 'can', sentence: '"hello" every morning.', regular: false },
  // { root: 'tocar', tense: 'present indicative',       subject: 'voce', conjugation: 'diz', frase: '"olá" todas as manhãs.', en: 'can', sentence: '"hello" every morning.', regular: false },
  // { root: 'tocar', tense: 'present indicative',       subject: 'elas', conjugation: 'dizem', frase: '"olá" todas as manhãs.', en: 'can', sentence: '"hello" every morning.', regular: false },
  // { root: 'tocar', tense: 'past perfect',          subject: 'eu',   conjugation: 'disse', frase: '"olá" ontem.', en: 'was able to', sentence: '"hello" yesterday.', regular: false },
  // { root: 'tocar', tense: 'past perfect',          subject: 'voce', conjugation: 'disse', frase: '"olá" ontem.', en: 'was able to', sentence: '"hello" yesterday.', regular: false },
  // { root: 'tocar', tense: 'past perfect',          subject: 'elas', conjugation: 'disseram', frase: '"olá" ontem.', en: 'was able to', sentence: '"hello" yesterday.', regular: false },
  // { root: 'tocar', tense: 'past imperfect', subject: 'eu',   conjugation: 'dizia', frase: '"viva e Deixe Viver."', en: 'could', sentence: '"live and let live."', regular: false },
  // { root: 'tocar', tense: 'past imperfect', subject: 'voce', conjugation: 'dizia', frase: '"viva e Deixe Viver."', en: 'could', sentence: '"live and let live."', regular: false },
  // { root: 'tocar', tense: 'past imperfect', subject: 'elas', conjugation: 'diziam', frase: '"viva e Deixe Viver."', en: 'could', sentence: '"live and let live."', regular: false },

  // { root: 'pegar', tense: 'present indicative',       subject: 'eu',   conjugation: 'digo', frase: '"olá" todas as manhãs.', en: 'can', sentence: '"hello" every morning.', regular: false },
  // { root: 'pegar', tense: 'present indicative',       subject: 'voce', conjugation: 'diz', frase: '"olá" todas as manhãs.', en: 'can', sentence: '"hello" every morning.', regular: false },
  // { root: 'pegar', tense: 'present indicative',       subject: 'elas', conjugation: 'dizem', frase: '"olá" todas as manhãs.', en: 'can', sentence: '"hello" every morning.', regular: false },
  // { root: 'pegar', tense: 'past perfect',          subject: 'eu',   conjugation: 'disse', frase: '"olá" ontem.', en: 'was able to', sentence: '"hello" yesterday.', regular: false },
  // { root: 'pegar', tense: 'past perfect',          subject: 'voce', conjugation: 'disse', frase: '"olá" ontem.', en: 'was able to', sentence: '"hello" yesterday.', regular: false },
  // { root: 'pegar', tense: 'past perfect',          subject: 'elas', conjugation: 'disseram', frase: '"olá" ontem.', en: 'was able to', sentence: '"hello" yesterday.', regular: false },
  // { root: 'pegar', tense: 'past imperfect', subject: 'eu',   conjugation: 'dizia', frase: '"viva e Deixe Viver."', en: 'could', sentence: '"live and let live."', regular: false },
  // { root: 'pegar', tense: 'past imperfect', subject: 'voce', conjugation: 'dizia', frase: '"viva e Deixe Viver."', en: 'could', sentence: '"live and let live."', regular: false },
  // { root: 'pegar', tense: 'past imperfect', subject: 'elas', conjugation: 'diziam', frase: '"viva e Deixe Viver."', en: 'could', sentence: '"live and let live."', regular: false },
  
  // { root: 'ficar', tense: 'present indicative',       subject: 'eu',   conjugation: 'digo', frase: '"olá" todas as manhãs.', en: 'can', sentence: '"hello" every morning.', regular: false },
  // { root: 'ficar', tense: 'present indicative',       subject: 'voce', conjugation: 'diz', frase: '"olá" todas as manhãs.', en: 'can', sentence: '"hello" every morning.', regular: false },
  // { root: 'ficar', tense: 'present indicative',       subject: 'elas', conjugation: 'dizem', frase: '"olá" todas as manhãs.', en: 'can', sentence: '"hello" every morning.', regular: false },
  // { root: 'ficar', tense: 'past perfect',          subject: 'eu',   conjugation: 'disse', frase: '"olá" ontem.', en: 'was able to', sentence: '"hello" yesterday.', regular: false },
  // { root: 'ficar', tense: 'past perfect',          subject: 'voce', conjugation: 'disse', frase: '"olá" ontem.', en: 'was able to', sentence: '"hello" yesterday.', regular: false },
  // { root: 'ficar', tense: 'past perfect',          subject: 'elas', conjugation: 'disseram', frase: '"olá" ontem.', en: 'was able to', sentence: '"hello" yesterday.', regular: false },
  // { root: 'ficar', tense: 'past imperfect', subject: 'eu',   conjugation: 'dizia', frase: '"viva e Deixe Viver."', en: 'could', sentence: '"live and let live."', regular: false },
  // { root: 'ficar', tense: 'past imperfect', subject: 'voce', conjugation: 'dizia', frase: '"viva e Deixe Viver."', en: 'could', sentence: '"live and let live."', regular: false },
  // { root: 'ficar', tense: 'past imperfect', subject: 'elas', conjugation: 'diziam', frase: '"viva e Deixe Viver."', en: 'could', sentence: '"live and let live."', regular: false },

  // { root: 'acabar', tense: 'present indicative',       subject: 'eu',   conjugation: 'digo', frase: '"olá" todas as manhãs.', en: 'can', sentence: '"hello" every morning.', regular: false },
  // { root: 'acabar', tense: 'present indicative',       subject: 'voce', conjugation: 'diz', frase: '"olá" todas as manhãs.', en: 'can', sentence: '"hello" every morning.', regular: false },
  // { root: 'acabar', tense: 'present indicative',       subject: 'elas', conjugation: 'dizem', frase: '"olá" todas as manhãs.', en: 'can', sentence: '"hello" every morning.', regular: false },
  // { root: 'acabar', tense: 'past perfect',          subject: 'eu',   conjugation: 'disse', frase: '"olá" ontem.', en: 'was able to', sentence: '"hello" yesterday.', regular: false },
  // { root: 'acabar', tense: 'past perfect',          subject: 'voce', conjugation: 'disse', frase: '"olá" ontem.', en: 'was able to', sentence: '"hello" yesterday.', regular: false },
  // { root: 'acabar', tense: 'past perfect',          subject: 'elas', conjugation: 'disseram', frase: '"olá" ontem.', en: 'was able to', sentence: '"hello" yesterday.', regular: false },
  // { root: 'acabar', tense: 'past imperfect', subject: 'eu',   conjugation: 'dizia', frase: '"viva e Deixe Viver."', en: 'could', sentence: '"live and let live."', regular: false },
  // { root: 'acabar', tense: 'past imperfect', subject: 'voce', conjugation: 'dizia', frase: '"viva e Deixe Viver."', en: 'could', sentence: '"live and let live."', regular: false },
  // { root: 'acabar', tense: 'past imperfect', subject: 'elas', conjugation: 'diziam', frase: '"viva e Deixe Viver."', en: 'could', sentence: '"live and let live."', regular: false },

  // { root: 'conseguir', tense: 'present indicative',       subject: 'eu',   conjugation: 'digo', frase: '"olá" todas as manhãs.', en: 'can', sentence: '"hello" every morning.', regular: false },
  // { root: 'conseguir', tense: 'present indicative',       subject: 'voce', conjugation: 'diz', frase: '"olá" todas as manhãs.', en: 'can', sentence: '"hello" every morning.', regular: false },
  // { root: 'conseguir', tense: 'present indicative',       subject: 'elas', conjugation: 'dizem', frase: '"olá" todas as manhãs.', en: 'can', sentence: '"hello" every morning.', regular: false },
  // { root: 'conseguir', tense: 'past perfect',          subject: 'eu',   conjugation: 'disse', frase: '"olá" ontem.', en: 'was able to', sentence: '"hello" yesterday.', regular: false },
  // { root: 'conseguir', tense: 'past perfect',          subject: 'voce', conjugation: 'disse', frase: '"olá" ontem.', en: 'was able to', sentence: '"hello" yesterday.', regular: false },
  // { root: 'conseguir', tense: 'past perfect',          subject: 'elas', conjugation: 'disseram', frase: '"olá" ontem.', en: 'was able to', sentence: '"hello" yesterday.', regular: false },
  // { root: 'conseguir', tense: 'past imperfect', subject: 'eu',   conjugation: 'dizia', frase: '"viva e Deixe Viver."', en: 'could', sentence: '"live and let live."', regular: false },
  // { root: 'conseguir', tense: 'past imperfect', subject: 'voce', conjugation: 'dizia', frase: '"viva e Deixe Viver."', en: 'could', sentence: '"live and let live."', regular: false },
  // { root: 'conseguir', tense: 'past imperfect', subject: 'elas', conjugation: 'diziam', frase: '"viva e Deixe Viver."', en: 'could', sentence: '"live and let live."', regular: false },
  
  // { root: 'dar', tense: 'present indicative',       subject: 'eu',   conjugation: 'digo', frase: '"olá" todas as manhãs.', en: 'can', sentence: '"hello" every morning.', regular: false },
  // { root: 'dar', tense: 'present indicative',       subject: 'voce', conjugation: 'diz', frase: '"olá" todas as manhãs.', en: 'can', sentence: '"hello" every morning.', regular: false },
  // { root: 'dar', tense: 'present indicative',       subject: 'elas', conjugation: 'dizem', frase: '"olá" todas as manhãs.', en: 'can', sentence: '"hello" every morning.', regular: false },
  // { root: 'dar', tense: 'past perfect',          subject: 'eu',   conjugation: 'disse', frase: '"olá" ontem.', en: 'was able to', sentence: '"hello" yesterday.', regular: false },
  // { root: 'dar', tense: 'past perfect',          subject: 'voce', conjugation: 'disse', frase: '"olá" ontem.', en: 'was able to', sentence: '"hello" yesterday.', regular: false },
  // { root: 'dar', tense: 'past perfect',          subject: 'elas', conjugation: 'disseram', frase: '"olá" ontem.', en: 'was able to', sentence: '"hello" yesterday.', regular: false },
  // { root: 'dar', tense: 'past imperfect', subject: 'eu',   conjugation: 'dizia', frase: '"viva e Deixe Viver."', en: 'could', sentence: '"live and let live."', regular: false },
  // { root: 'dar', tense: 'past imperfect', subject: 'voce', conjugation: 'dizia', frase: '"viva e Deixe Viver."', en: 'could', sentence: '"live and let live."', regular: false },
  // { root: 'dar', tense: 'past imperfect', subject: 'elas', conjugation: 'diziam', frase: '"viva e Deixe Viver."', en: 'could', sentence: '"live and let live."', regular: false },
]

export default cards
